name: AI PR Review (DeepSeek)

on:
  pull_request_target:      # нужен, чтобы иметь доступ к секретам репозитория
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  review:
    runs-on: ubuntu-latest

    env:
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}
      PR_NUMBER: ${{ github.event.pull_request.number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # берём код из ветки PR
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run AI review (DeepSeek)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: npm run review
